### ISSUE TITLE
[S3 Standard Bucket] Only root user can change or delete bucket policy

### ISSUE THREAD

**Issue by yukihato** [japan-d2/secure-stack-template-aws#34]
With the following policy description, the policy cannot be changed or deleted in `OrganizationAccountAccessRole`.
As a result, only root user can change or delete.

```
          - Sid: Deny-changing-bucket-permission
            Effect: Deny
            NotPrincipal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:role/OrganizationAccountAccessRole
            Action:
              - s3:DeleteBucketPolicy
              - s3:PutBucketPolicy
              - s3:PutBucketPublicAccessBlock
            Resource: !GetAtt StandardBucket.Arn
```

The following will work, but cannot be used as a policy because session names are not fixed and wildcards are not allowed.

```
          - Sid: Deny-changing-bucket-permission
            Effect: Deny
            NotPrincipal:
              AWS: 
                - !Sub arn:aws:sts::${organization-account}:assumed-role/OrganizationAccountAccessRole/${session-name}
                - !Sub arn:aws:iam::${AWS::AccountId}:role/OrganizationAccountAccessRole
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - s3:DeleteBucketPolicy
              - s3:PutBucketPolicy
              - s3:PutBucketPublicAccessBlock
            Resource: !GetAtt StandardBucket.Arn
```

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_notprincipal.html#specifying-notprincipal
